# Generated by Django 4.2.11 on 2024-04-20 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id_administrator', models.AutoField(primary_key=True, serialize=False, verbose_name='id administrator')),
                ('first_name', models.CharField(max_length=500, verbose_name='first name')),
                ('last_name', models.CharField(max_length=500, verbose_name='last name')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
    ]
