# Generated by Django 4.2.11 on 2024-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operators',
            fields=[
                ('id_operator', models.AutoField(primary_key=True, serialize=False, verbose_name='id_operator')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=300)),
                ('birth_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'operators',
            },
        ),
    ]
