# Generated by Django 4.2.11 on 2024-04-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operators',
            table='Operators',
        ),
    ]
