# Generated by Django 5.0.3 on 2024-04-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operators',
            table='Operators',
        ),
    ]
