# Generated by Django 4.2.11 on 2024-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_alter_operators_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='admission_date',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
