# Generated by Django 4.2.11 on 2024-04-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServicePromotion',
            fields=[
                ('id_service_promotion', models.AutoField(primary_key=True, serialize=False)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_promotion',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id_service_type', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='ServicePromotionService',
            fields=[
                ('id_service_promotions_service', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('service_promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicepromotion')),
            ],
            options={
                'db_table': 'service_promotion_service',
            },
        ),
        migrations.AddField(
            model_name='servicepromotion',
            name='service',
            field=models.ManyToManyField(related_name='promotions', through='services.ServicePromotionService', to='services.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype'),
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id_invoice_service', models.AutoField(primary_key=True, serialize=False)),
                ('final_service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
            options={
                'db_table': 'invoice_service',
            },
        ),
    ]
