# Generated by Django 4.2.11 on 2024-04-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
    ]
