# Generated by Django 5.0.3 on 2024-04-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicepromotion',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicepromotionservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicepromotionservice',
            name='service_promotion',
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='id_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='id service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='id_service_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='services.servicetype', verbose_name='id service type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepromotion',
            name='id_service',
            field=models.ManyToManyField(related_name='promotions', through='services.ServicePromotionService', to='services.service', verbose_name='id service'),
        ),
        migrations.AddField(
            model_name='servicepromotionservice',
            name='id_service',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='id service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepromotionservice',
            name='id_service_promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='services.servicepromotion', verbose_name='id service promotion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='final_service_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='final service price'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='id_invoice_service',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id invoice service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id_service',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id service'),
        ),
        migrations.AlterField(
            model_name='servicepromotion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='servicepromotion',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='discount rate'),
        ),
        migrations.AlterField(
            model_name='servicepromotion',
            name='id_service_promotion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id service promotion'),
        ),
        migrations.AlterField(
            model_name='servicepromotionservice',
            name='id_service_promotions_service',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id service promotions service'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='id_service_type',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id service type'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_name',
            field=models.CharField(max_length=150, verbose_name='service name'),
        ),
    ]
