# Generated by Django 4.2.11 on 2024-04-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCustomer',
            fields=[
                ('id_service_customer', models.AutoField(primary_key=True, serialize=False, verbose_name='id service customer')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='customer')),
            ],
        ),
    ]
