# Generated by Django 4.2.11 on 2024-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_service_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_initial_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='service initial price'),
            preserve_default=False,
        ),
    ]
