# Generated by Django 4.2.11 on 2024-04-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecustomer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicecustomer',
            table='service_customer',
        ),
    ]
