# Generated by Django 4.2.11 on 2024-04-04 15:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.AutoField(primary_key=True, serialize=False, verbose_name='id_package')),
                ('name', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='PackageDiscount',
            fields=[
                ('id_package_discount', models.AutoField(primary_key=True, serialize=False, verbose_name='id_package_discount')),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='discount_rate')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('id_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='packages.package', verbose_name='id_package')),
            ],
            options={
                'db_table': 'package_discount',
            },
        ),
    ]
