# Generated by Django 4.2.11 on 2024-04-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCustomer',
            fields=[
                ('id_package_customer', models.AutoField(primary_key=True, serialize=False, verbose_name='id package customer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package', verbose_name='package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'package_customer',
            },
        ),
    ]
