# Generated by Django 4.2.11 on 2024-04-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_service_initial_price'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='package_service1', to='services.service', verbose_name='Package Service 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='service2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='package_service2', to='services.service', verbose_name='Package Service 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='service3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_service3', to='services.service', verbose_name='Package Service 3'),
        ),
        migrations.AddField(
            model_name='package',
            name='service4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_service4', to='services.service', verbose_name='Package Service 4'),
        ),
    ]
